name: "vim help tag name check"
on: push
jobs:
  tagname:
    name: Check tag name conflict
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Help tag check
        uses: tsuyoshicho/action-vimhelp-tagname-check@master
